### ISSUE TITLE
TO DO Sep 16

### ISSUE THREAD

**Issue by dicook** [numbats/cassowaryr#2]
- [x]  drawing alpha hull, convex hull, mst
- [x] music, economic, time series: compute features, and then compute scagnostics (Ursula)
- [x] example code to plot scatterplot matrix, and make interactive
- [x] new indexes codes: 
      - stripes (Di)
      - robust outlying, clumpy
      - (fix) striated
- [ ]  cran checks 
- [ ] vignette needs expanding to minimal level
- [x]  test code for major functions: 
- [x]  check clumpy calculation
- [x]  simulated data, maybe based on the current features data, and examine the distributions of the scagnostics. they should range between 0-1, and ideally sort of uniform.
- [x]  name of sc_pairwise change to calc_scags_wide; make example code smaller, and run within 5s
- [ ]  pkgdown reference functions, add features data
- [ ] cassowaryr paper

**Comment by dicook** [comment]
The calc_scags_wide example should probably be a multivariate data set rather than the datasurus, where all pairs of variables would be interesting.

**Comment by uschiLaa** [comment]
Looks like pk data is not in the package?

**Comment by dicook** [comment]
it’s there now. Sorry.

> On 27 Sep 2021, at 5:48 pm, uschiLaa ***@***.***> wrote:
> 
> 
> Looks like pk data is not in the package?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> 

cheers,
Di

---
Dianne Cook
***@***.***
