### ISSUE TITLE
progress_bar not initialized

### ISSUE THREAD

**Issue by uschiLaa** [numbats/cassowaryr#3]
Error in cassowaryr::calc_scags_wide(feats_birdsong) : 
  Objekt 'progress_bar' nicht gefunden
(Object not found)
Should be fixed in line 20 of calculate.R

**Comment by dicook** [comment]
Oh, this was a change I made yesterday that was a mistake. I’ll put that dependency back in.

**Comment by dicook** [comment]
Can you check this again - I think I've fixed this. I've cleaning code too vociferously

**Comment by dicook** [comment]
I just added some code in the paper-avast repo, and it seems to work. 

The paper-vaast repo needs a name change. And the paper name needs to have Harriet- removed.

**Comment by uschiLaa** [comment]
Yes, this works now!
