### ISSUE TITLE
Constant values

### ISSUE THREAD

**Issue by uschiLaa** [numbats/cassowaryr#9]
We need to decide how to handle constant values for a variable. Currently the unitize function will "transform" them to NaN (because of zero range) and scree  will throw an error.

**Comment by dicook** [comment]
Which code/data is throwing the error? Is this occurring when there is an L-shape? 

If one variable has constant values we could print a message reporting the culprit and set the scagnostics all to 0, or earn that the variable has been removed.

**Comment by uschiLaa** [comment]
This happens for me with anscombe once outliers have been removed (still x1 vs x4 that is being problematic).

**Comment by dicook** [comment]
Ah, ok.

Think best option is to remove the variable and give a message.

**Comment by uschiLaa** [comment]
I agree, but it looks like this will require a bit of extra structure, same as for the other errors, we want an option for catching errors when running via calc_scacs_wide. Maybe calc_scags could catch errors from original_and_robust and return a tibble with all NULL in that case?

**Comment by uschiLaa** [comment]
Actually this happens with the time series data as well when using features from feasts, but might also indicate issues with outlier removal in this case. Looking at zero_run_mean vs spikiness about 1/3 of points is taken out as outliers, resulting in unique value along zero_run_mean.

**Comment by uschiLaa** [comment]
I've put in a simple solution which will record all scagnostics as NA if there is a constant variable after outlier removal for some combination. Not ideal but otherwise would have to modify several functions for proper messaging of what was missing.
